name = "app"
version = "1.0.0"

[dependencies]
gleam_erlang = ">= 1.3.0 and < 2.0.0"
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
logging = ">= 1.3.0 and < 2.0.0"
rlog = { path = "../.." }

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
